---

name: ChangelogChecker
"on":
  pull_request:
    types: [review_requested, ready_for_review]
    branches:
      - develop
      - master
jobs:
  build:
    if: startsWith(github.head_ref, 'renovate/') != true
    name: Check Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Changelog checker
        uses: Zomzog/changelog-checker@9f2307a9f44fcbde2147bdb8a7fa724aaaaae16a
        with:
          fileName: CHANGELOG.md
          checkNotification: Simple
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
